### PR TITLE
Fix crash on log files with search strategies defined

### PR DESCRIPTION
**Pull request by CADBIMDeveloper**
Hi!

I have a bunch of models, where I defined few search strategies (I know this could be a bad practice, but it gives me up to 25% performance boost and I test it on each new OR-Tools release). In that case initial optimization model block starts with the summary of applied search strategies, e.g:
```
Initial optimization model '': (model_fingerprint: 0x43663dbe1b9da445)
Search strategy: on 11 variables, CHOOSE_FIRST, SELECT_MIN_VALUE
Search strategy: on 11 variables, CHOOSE_FIRST, SELECT_MIN_VALUE
Search strategy: on 11 variables, CHOOSE_FIRST, SELECT_MIN_VALUE
Search strategy: on 7 variables, CHOOSE_FIRST, SELECT_MIN_VALUE
...
```

And only then there is a variables block.

This PR fixes a crash of the logs analyzer when it doesn't find `#Variables: ` in `self.lines[0]`

P.S. Thanks for that great tool!

### CODE REVIEW

**Comment by d-krupke** [comment]
Great, thank you so much. I will check it out next week when I return home. Looks fine from my phone.

Regarding "bad practice": They should only influence a single worker so it should be fine. I never experienced any serious advantage in doing so and there is some risk in getting in the way of the pre-tuned solver with the next version. However, if it gives you a 25% boost and you check it with each update - amazing. I would be very interested in the use case if you are able to share that.

Best,
Dominik

**Comment by d-krupke** [comment]
Works nicely, thanks again! If you are allowed to share the use case where the search strategy gives you a 25% boost, I would be happy about a mail to krupked@gmail.com :)

**Comment by CADBIMDeveloper** [comment]
Hi Dominik!

Unfortunately, I can share only the idea behind... :-(

I have a bunch of variables $[x_1, x_2, ..., x_n]$ which are clustered, like ${x_1, x_2, x_3} \in C_1$, ${x_4, x_5} \in C_2$ and so on. In each cluster I apply symmetry breaking constraints, something like $\forall i, \forall j: x_j \in C_i\ (except\ last\ j\ in\ C_i): x_j \leq x_{j+1}$. I also have a bunch of variables $[y_1, y_2, ..., y_n]$ which are indirectly dependent on $x_i$. It's likely, that most  of the following constraints would be satisfied: $\forall i, i < n: y_i \leq y_{i+1}$ (but not all of them!). In my case $x_i$ are booleans, and $y_i$ are integers from discrete domain. I'm applying decision strategy to $y_i$.

I believe, improving the symmetry breaking rules will be more efficient, but 1 - current solution is quite fast, 2 - it would be very complicated.

P.S. Currently I'm using OR-Tools 9.10 and waiting for 9.12 with solution callbacks fixes.

**Comment by d-krupke** [comment]
> Hi Dominik!
> 
> Unfortunately, I can share only the idea behind... :-(
> 
> I have a bunch of variables [ x 1 , x 2 , . . . , x n ] which are clustered, like x 1 , x 2 , x 3 ∈ C 1 , x 4 , x 5 ∈ C 2 and so on. In each cluster I apply symmetry breaking constraints, something like ∀ i , ∀ j : x j ∈ C i   ( e x c e p t   l a s t   j   i n   C i ) : x j ≤ x j + 1 . I also have a bunch of variables [ y 1 , y 2 , . . . , y n ] which are indirectly dependent on x i . It's likely, that most of the following constraints would be satisfied: ∀ i , i < n : y i ≤ y i + 1 (but not all of them!). In my case x i are booleans, and y i are integers from discrete domain. I'm applying decision strategy to y i .
> 
> I believe, improving the symmetry breaking rules will be more efficient, but 1 - current solution is quite fast, 2 - it would be very complicated.
> 
> P.S. Currently I'm using OR-Tools 9.10 and waiting for 9.12 with solution callbacks fixes.

I totally understand. The idea is already insightful to me, thanks for sharing!

**Pull request merged**
